# Week 5 Assignment Answer Key

This notebook provides Python solutions for the three required functions.

In [1]:
import numpy as np

## 1. findSDArray(A)
Find the standard deviation of each column and ignore NaN values.

In [2]:
def findSDArray(A):
    """
    Return the standard deviation of each column in a NumPy array,
    ignoring NaN values.
    """
    return np.nanstd(A, axis=0)

## 2. normalizeArray(A)
Divide each column by its own column standard deviation.

In [3]:
def normalizeArray(A):
    """
    Divide each column of A by its column standard deviation,
    ignoring NaN values when calculating standard deviation.
    """
    A = np.array(A, dtype=float)
    sd = findSDArray(A)
    return A / sd

## 3. negativesToZero(A)
Replace negative values with zero.

In [4]:
def negativesToZero(A):
    """
    Return an array where all negative values are changed to 0.
    """
    A = np.array(A, copy=True)
    A[A < 0] = 0
    return A

## Test Example

In [5]:
A = np.array([
    [0.31903967, 0.49385635],
    [0.13983727, -0.40484725]
])

print("Original array:")
print(A)

print("\nStandard deviation of columns:")
print(findSDArray(A))

print("\nNormalized array:")
print(normalizeArray(A))

print("\nNegatives changed to zero:")
print(negativesToZero(A))

Original array:
[[ 0.31903967  0.49385635]
 [ 0.13983727 -0.40484725]]

Standard deviation of columns:
[0.0896012 0.4493518]

Normalized array:
[[ 3.56066292  1.09904166]
 [ 1.56066292 -0.90095834]]

Negatives changed to zero:
[[0.31903967 0.49385635]
 [0.13983727 0.        ]]
