# HW05 NumPy Matrix Answer Key

Runnable instructor answer key notebook.

Problems 5–10 use the matrix shown in the assignment.Type this matrix in MATLAB and use MATLAB to carry out the following

In [1]:
import numpy as np
A = np.array([[3, 7, -4, 12],
              [-5, 9, 10, 2],
              [6, 13, 8, 11],
              [15, 5, 4, 1]])
print(A)

[[ 3  7 -4 12]
 [-5  9 10  2]
 [ 6 13  8 11]
 [15  5  4  1]]


Problem 5.
a. Create a vector v consisting of the elements in the second column of A.
b. Create a vector w consisting of the elements in the second row of A.

In [2]:
v = A[:, 1]
w = A[1, :]
print('v = second column:', v)
print('w = second row:', w)

v = second column: [ 7  9 13  5]
w = second row: [-5  9 10  2]


Problem 6.
a. Create a 4 X 3 array B consisting of all elements in the second through fourth columps of A. ; .
b. Create a 3 X 4 array C consisting of all elements in the second through fourth rows of A.
c. Create 2 X 3 array D consisting of all elements in the first two rows

In [3]:
C = A[0:2, 1:4]
print(C)

[[ 7 -4 12]
 [ 9 10  2]]


In [4]:
B = A[:, 1:4]
C = A[1:4, :]
D = A[0:2, 1:4]
print('B =\n', B)
print('C =\n', C)
print('D =\n', D)

B =
 [[ 7 -4 12]
 [ 9 10  2]
 [13  8 11]
 [ 5  4  1]]
C =
 [[-5  9 10  2]
 [ 6 13  8 11]
 [15  5  4  1]]
D =
 [[ 7 -4 12]
 [ 9 10  2]]


Problem 7 (optional).Compute the length and absolute value of the following vectors:

In [5]:
x = np.array([2, 4, 7])
y = np.array([2, -4, 7])
z = np.array([5 + 3j, -3 + 4j, 2 - 7j])
for name, vector in [('x', x), ('y', y), ('z', z)]:
    print(name, 'length =', len(vector))
    print(name, 'absolute values =', np.abs(vector))

x length = 3
x absolute values = [2 4 7]
y length = 3
y absolute values = [2 4 7]
z length = 3
z absolute values = [5.83095189 5.         7.28010989]


In [6]:
x = np.array([2, 4, 7])
y = np.array([2, -4, 7])
z = np.array([5 + 3j, -3 + 4j, 2 - 7j])
for name, vector in [('x', x), ('y', y), ('z', z)]:
    print("length is", vector.size)
    print("absolute value is", np.abs(vector))

length is 3
absolute value is [2 4 7]
length is 3
absolute value is [2 4 7]
length is 3
absolute value is [5.83095189 5.         7.28010989]


Problem 8.
a. Find the maximum and minimum values in each column.
b. Find the maximum and minimum values in each row,

In [7]:
print('Row maximums:', A.max(axis=0))
print('Row minimums:', A.min(axis=0))
print('Column maximums:', A.max(axis=1))
print('Column minimums:', A.min(axis=1))

Row maximums: [15 13 10 12]
Row minimums: [-5  5 -4  1]
Column maximums: [12 10 13 15]
Column minimums: [-4 -5  6  1]


Problem 9.
a. Sort each column and store the result in an array B.
b, Sort each row and store the result in an array C.
c. Add each column and store the result in an array D.
d. Add each row and store the result in an array EB.

In [8]:
B = np.sort(A, axis=0)  # sort each column
C = np.sort(A, axis=1) ## find the ascending default code

In [9]:
B = np.sort(A, axis=0)  # sort each column
C = np.sort(A, axis=1)  # sort each row
D = A.sum(axis=0)       # add each column
E = A.sum(axis=1)       # add each row
print('B =\n', B)
print('C =\n', C)
print('D =', D)
print('E =', E)

B =
 [[-5  5 -4  1]
 [ 3  7  4  2]
 [ 6  9  8 11]
 [15 13 10 12]]
C =
 [[-4  3  7 12]
 [-5  2  9 10]
 [ 6  8 11 13]
 [ 1  4  5 15]]
D = [19 34 18 26]
E = [18 16 38 25]


Problem 10.
a. Select just the second row of B. b. Evaluate the sum of the second row of B.
c. Multiply the second column of B and the first column of A element by element.
d. Evaluate the maximum value in the vector resulting from element-by- element multiplication of the second colutnn of B with the first of A.
e. Use element-by-element division to divide the first row of A by the first three elements of the third column of B, Evaluate the sum of thé elements of the resulting vector.

In [10]:
A2 = np.array([[1, 4, 2],
               [2, 4, 100],
               [7, 9, 7],
               [3, np.pi, 42]], dtype=float)

In [11]:
B2 = np.log(A2)
print(B2)

[[0.         1.38629436 0.69314718]
 [0.69314718 1.38629436 4.60517019]
 [1.94591015 2.19722458 1.94591015]
 [1.09861229 1.14472989 3.73766962]]


In [13]:
a = B2[1, :]
b = B2[1, :].sum()
c = B2[:, 1] * A2[:, 0]
d = c.max()
e_cal = A2[0, :] / B2[:3, 2]
e = e_cal.sum()

print('A Matrix =\n', A2)
print('B Matrix =\n', B2)
print('a = second row of B:', a)
print('b = sum of second row of B:', b)
print('c = second column of B times first column of A:', c)
print('d = max of c:', d)
print('e_vector =', e_cal)
print('e = sum:', e)

A Matrix =
 [[  1.           4.           2.        ]
 [  2.           4.         100.        ]
 [  7.           9.           7.        ]
 [  3.           3.14159265  42.        ]]
B Matrix =
 [[0.         1.38629436 0.69314718]
 [0.69314718 1.38629436 4.60517019]
 [1.94591015 2.19722458 1.94591015]
 [1.09861229 1.14472989 3.73766962]]
a = second row of B: [0.69314718 1.38629436 4.60517019]
b = sum of second row of B: 6.684611727667928
c = second column of B times first column of A: [ 1.38629436  2.77258872 15.38057204  3.43418966]
d = max of c: 15.380572041353537
e_vector = [1.44269504 0.86858896 1.02779668]
e = sum: 3.3390806894349683
