# HW5 NumPy Matrix Answer Key

Runnable instructor answer key notebook.

Problems 5–10 use the matrix shown in the assignment.

In [2]:
import numpy as np
A = np.array([[3, 7, -4, 12],
              [-5, 9, 10, 2],
              [6, 13, 8, 11],
              [15, 5, 4, 1]])
print(A)

[[ 3  7 -4 12]
 [-5  9 10  2]
 [ 6 13  8 11]
 [15  5  4  1]]


Problem 5.

In [ ]:
v = A[:, 1]
w = A[1, :]
print('v = second column:', v)
print('w = second row:', w)

v = second column: [ 7  9 13  5]
w = second row: [-5  9 10  2]


Problem 6.

In [ ]:
B = A[:, 1:4]
C = A[1:4, :]
D = A[0:2, 1:4]
print('B =\n', B)
print('C =\n', C)
print('D =\n', D)

B =
 [[ 7 -4 12]
 [ 9 10  2]
 [13  8 11]
 [ 5  4  1]]
C =
 [[-5  9 10  2]
 [ 6 13  8 11]
 [15  5  4  1]]
D =
 [[ 7 -4 12]
 [ 9 10  2]]


Problem 7.

In [ ]:
x = np.array([2, 4, 7])
y = np.array([2, -4, 7])
z = np.array([5 + 3j, -3 + 4j, 2 - 7j])
for name, vector in [('x', x), ('y', y), ('z', z)]:
    print(name, 'length =', len(vector))
    print(name, 'absolute values =', np.abs(vector))

x length = 3
x absolute values = [2 4 7]
y length = 3
y absolute values = [2 4 7]
z length = 3
z absolute values = [5.83095189 5.         7.28010989]


Problem 8.

In [ ]:
print('Column maximums:', A.max(axis=0))
print('Column minimums:', A.min(axis=0))
print('Row maximums:', A.max(axis=1))
print('Row minimums:', A.min(axis=1))

Column maximums: [15 13 10 12]
Column minimums: [-5  5 -4  1]
Row maximums: [12 10 13 15]
Row minimums: [-4 -5  6  1]


Problem 9.

In [ ]:
B = np.sort(A, axis=0)  # sort each column
C = np.sort(A, axis=1)  # sort each row
D = A.sum(axis=0)       # add each column
E = A.sum(axis=1)       # add each row
print('B =\n', B)
print('C =\n', C)
print('D =', D)
print('E =', E)

B =
 [[-5  5 -4  1]
 [ 3  7  4  2]
 [ 6  9  8 11]
 [15 13 10 12]]
C =
 [[-4  3  7 12]
 [-5  2  9 10]
 [ 6  8 11 13]
 [ 1  4  5 15]]
D = [19 34 18 26]
E = [18 16 38 25]


Problem 10.

In [3]:
A2 = np.array([[1, 4, 2],
               [2, 4, 100],
               [7, 9, 7],
               [3, np.pi, 42]], dtype=float)
B2 = np.log(A2)

print(B2)

[[0.         1.38629436 0.69314718]
 [0.69314718 1.38629436 4.60517019]
 [1.94591015 2.19722458 1.94591015]
 [1.09861229 1.14472989 3.73766962]]


In [9]:
print('A Matrix =\n', A2)
print('B Matrix =\n', B2)

A Matrix =
 [[  1.           4.           2.        ]
 [  2.           4.         100.        ]
 [  7.           9.           7.        ]
 [  3.           3.14159265  42.        ]]
B Matrix =
 [[0.         1.38629436 0.69314718]
 [0.69314718 1.38629436 4.60517019]
 [1.94591015 2.19722458 1.94591015]
 [1.09861229 1.14472989 3.73766962]]


In [5]:
a = B2[1, :] #second row of B:
b = B2[1, :].sum() #sum of second row of B
c = B2[:, 1] * A2[:, 0]#second column of B times first column of A:
d = c.max()#max of c
e_vector = A2[0, :] / B2[:3, 2]#e_vector: first column of A divide first three rows from the third column B
e = e_vector.sum()#e = sum

In [12]:
A2[0, :] #array[rows, columns]

array([1., 4., 2.])

In [13]:
B2[:3, 2] #rows 0, 1, and 2 (the first 3 rows) column index 2

array([0.69314718, 4.60517019, 1.94591015])

In [10]:
print('a = second row of B:', a)
print('b = sum of second row of B:', b)
print('c = second column of B times first column of A:', c)
print('d = max of c:', d)
print('e_vector =', e_vector)
print('e = sum:', e)

a = second row of B: [0.69314718 1.38629436 4.60517019]
b = sum of second row of B: 6.684611727667928
c = second column of B times first column of A: [ 1.38629436  2.77258872 15.38057204  3.43418966]
d = max of c: 15.380572041353537
e_vector = [1.44269504 0.86858896 1.02779668]
e = sum: 3.3390806894349683
